version: '3'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: your_username
      POSTGRES_PASSWORD: your_password
      POSTGRES_DB: your_database
    volumes:
      - ./DATA:/var/lib/postgresql/data
  pargres:
    build:
      context: ./Project
      dockerfile: Dockerfile
    depends_on:
      - db
    volumes:
      - ./Project:/pargres-0.1
    environment:
      - WORKDIR=/path_to_workdir
      - NODEFILE=/path_to_nodefile
      - POSTGRES_HOME=/path_to_postgres_home
      - DBNAME=your_db_name
      - DBLOGIN=your_db_login
      - DBPASSWORD=your_db_password
      - DB_HOST=db
      - DB_PORT=your_port
